language: go
sudo: required
go:
- '1.14'
services:
- docker
install: true
script: make travis -e VERSION=$TRAVIS_BRANCH
deploy:
  provider: releases
  api_key:
    secure: QlZJ9ki86vBUzCw5V60G11plc3kqEgEruW7go8+PBCAuWswGsD7O96uTJbDx4db+4vT4meiv8G4o43PzlHeFX4PazmN8cTn44fOTYI0Q01YFH2VX8tz2424qsnihOf9osAUAtlHZ4QngqQm+VA9zxgP7q9ckDg9bPgNYMtvlKwlw3XZhirY5YX9qo+uSoSpmQ8dNTCoohgCgP76NGdPJ59Cgz/T7a3iVjsv9j6iFQR3BikJjlmQP5IDdMLZgJsmMo2m0vszdPP7oTsDVUcrj2FQUBNGA5pkJCsGzuNjZ/C8vvRmFZO3dBHx0eGwV9UtPseuONRLr9gk6QdlmnnNtxzqZw3FTlMYxfLy6VxdjrLYO+KnixhQEQHG1HvjjCvp4Y1fSUWUiLWZuNfZBSkcxra0X6V6mfaLFlOftlZWO1b/ac4jecEJQcxJ8lglLXDargENLQatlGhkzOpL73gNux5yUq38hLAkbzX3m/u/ZfgJ9RBJuobuRRlKDPHC2KNAjBfD06Wgj/2PDmQNVPMqqGoWCq3h1RIOSSqJMvSYhK6xoIOP2aR9SDnldWc70o5scpfMwK8PBwZN8f4NARBMIPbsWXu1PLsUJ+oBJjJObxETYvVcrYUMT+vV0eEpza0Hvzh4foIJ8Qro013LQbXrXXdiE8qm95KyqRxRKlXV6r1k=
  file_glob: true
  file: './dist/postgresql_exporter.*.tar.gz'
  on:
    repo: andywow/postgresql_exporter
    tags: true
  skip_cleanup: 'true'
