language: go
sudo: required
go:
- '1.14'
services:
- docker
install: true
script: make travis -e VERSION=$TRAVIS_BRANCH
deploy:
  provider: releases
  api_key:
    secure: hacA5GnsPoNTZJCvW4IZSQaFMelvtsjm5XuTdsirkSbz8dhvVdsbOI7jFk7tNH/uBs2FzUK7qII38hhG4/2Unfv37JPo1+AvtCB6CDgNBiAm3MPrL2Zwmt1CblVxifN0aXx6A6fCdNQfHI2ivJKdOPTFY40XkVjtCTJ3Uwz34Wocu7jHyy2h+WrijATu3sGIlZw8VRRyBZrjZvSJq3qtv9o8QIFjyD2Q5OO9CjFIs+GUWcvp3n/2D10Qzs9ERb77N55XwOY/OzpxktQCG1U6aB22ELCvVEsDtVjjjkFKfUFiV7qsZA1iJhl49bKTlSkRZj0tNXf+wCzEphiLW6UZfc1w350/Gr44j6uHModj6+O48zl/y26z3oxPGmOu2lSRmPJTAToK3VapZLOZ3wO/Vw6Bq9MRpWIbCfTIkXZ0GCFyr10jQmRuSOoEUIqPQJYfKuIg4oc3zKFGHwaVp3ilnLdsnIjCTfTxgC1NuornR7KWvI++ZHNrPTboXeCKRxUR1KIlHQd78cTl8CaMQk8Ov4ZiGWAEZYg+97KxO4x0+M2A2d7jKO4lCCuB3RovfcZ1t/oHOedXfy7AjODiULx+4zxD0qKeMxcCOqSrA4yg+cP6of21yVyZgMlUkuTMnq6ZJjsC+a/onqGrJjdSWnBkcYURb5OcqtEjxQOor+FVF9I=
  file_glob: true
  file: './dist/clickhouse_exporter.*.tar.gz'
  on:
    repo: andywow/clickhouse_exporter
    tags: true
  skip_cleanup: 'true'
