[[metric]]
context = "database"
labels = [ "database"]
metricsdesc = { size_bytes= "Size in bytes" }
request = "SELECT pg_database.datname as database, pg_database_size(pg_database.datname) as size_bytes FROM pg_database"

[[metric]]
context = "replication"
labels = []
metricsdesc = { lag= "Replication lag behind master in seconds" }
request = "SELECT coalesce(EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())), 0) as lag"

[[metric]]
context = "postmaster"
labels = []
metricsdesc = { start_time_seconds = "Time at which postmaster started" }
request = """
  SELECT EXTRACT(
    EPOCH FROM (SELECT pg_postmaster_start_time from pg_postmaster_start_time())
  ) as start_time_seconds
"""

[[metric]]
context = "statio_user_tables"
labels = [ "database", "schema", "table" ]
metricsdesc = { heap_blks_read= "Number of disk blocks read from this table", heap_blks_hit= "Number of buffer hits in this table", idx_blks_read="Number of disk blocks read from all indexes on this table", idx_blks_hit="Number of buffer hits in all indexes on this table", toast_blks_read="Number of disk blocks read from this table's TOAST table (if any)", toast_blks_hit="Number of buffer hits in this table's TOAST table (if any)", tidx_blks_read="Number of disk blocks read from this table's TOAST table indexes (if any)", tidx_blks_hit="Number of buffer hits in this table's TOAST table indexes (if any)" }
request = """
  SELECT current_database() as database, schemaname as schema, relname as table,
  heap_blks_read, heap_blks_hit,
  coalesce(idx_blks_read, 0) as idx_blks_read, coalesce(idx_blks_hit, 0) as idx_blks_hit,
  coalesce(toast_blks_read, 0) as toast_blks_read, coalesce(toast_blks_hit, 0) as toast_blks_hit,
  coalesce(tidx_blks_read, 0) as tidx_blks_read, coalesce(tidx_blks_hit, 0) as tidx_blks_hit
  FROM pg_statio_user_tables
"""
