[[metric]]
context = "table"
labels = [ "database", "table" ]
metricsdesc = { bytes = "Size in butes", parts = "Parts count", rows = "Rows count" }
request = """
  select database, table, sum(bytes) as bytes, count() as parts, sum(rows) as rows
  from system.parts
  where active = 1
  group by database, table
"""
